<?php
use Moyasar\Magento2\Admin\ButtonElement;

/**
 * @see \Moyasar\Magento2\Admin\ButtonElement
 * @var ButtonElement $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="mysr-button-container">
    <div dir="ltr" trbidi="on">
        <a class="action-default"
           href="<?= /* @noEscape */ $block->escapeUrl($block->getButtonUrl()) ?>"
           target="_blank"><?= $block->escapeHtml($block->getButtonLabel()) ?></a>
    </div>
</div>
<style>
    .mysr-button-container {

    }
</style>
